-- PARTE 1: 100 productos
DELETE FROM products;
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES
INSERT INTO products (id, name, description, price, original_price, category, subcategory, brand, image, badge, points, stock, in_stock, rating, reviews) VALUES;
